apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SECRET_KEY: c2VjcmV0LWtleS12YWx1ZQ==
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9lbGVhcm5pbmc=
  PAYMENT_API_KEY: cGF5bWVudC1hcGkta2V5LXZhbHVl